version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=petpal
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petpal
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: